services:
  frontend:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: auth-frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ../:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=/api/api
      - VITE_AUTH_GITHUB_URL=/api/api/auth/github/login
      - VITE_SESSION_TIMEOUT=1800000
      - VITE_SESSION_RENEWAL_THRESHOLD=300000
      - VITE_LOG_LEVEL=debug

  nginx:
    image: nginx:alpine
    container_name: auth-nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    depends_on:
      - frontend

networks:
  app-network:
    driver: bridge