services:
  frontend:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: auth-frontend
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ../:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=/api/api
      - VITE_AUTH_GITHUB_URL=/api/api/auth/github/login
      - VITE_SESSION_TIMEOUT=1800000
      - VITE_SESSION_RENEWAL_THRESHOLD=300000
      - VITE_LOG_LEVEL=debug

networks:
  app-network:
    driver: bridge